// File generated by FlutterFire CLI.
// Run: flutterfire configure
// See: https://firebase.flutter.dev/docs/cli

// ⚠️  PLACEHOLDER — replace this file with the one generated by FlutterFire CLI
// after you have created your Firebase project.
//
// Steps:
//   1. Go to https://console.firebase.google.com and create a project called "OuttaDebt"
//   2. Enable Email/Password and Google authentication methods
//   3. Create a Cloud Firestore database (start in test mode, then secure with rules)
//   4. Install the FlutterFire CLI:  dart pub global activate flutterfire_cli
//   5. In the project root run:  flutterfire configure
//   6. This file will be replaced with your real options automatically.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // ── Replace all values below after running `flutterfire configure` ────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLy4-x7y52J4iph05JxDHwOBstmLLzfxg',
    appId: '1:862847817672:web:58395324855c2ccbb192fd',
    messagingSenderId: '862847817672',
    projectId: 'outtadebtdb',
    authDomain: 'outtadebtdb.firebaseapp.com',
    storageBucket: 'outtadebtdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVCHo7qN7uKSCrDd2FhZDEFsd0U4Y_zO8',
    appId: '1:862847817672:android:6de7211b0d549209b192fd',
    messagingSenderId: '862847817672',
    projectId: 'outtadebtdb',
    storageBucket: 'outtadebtdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFd9i8yYfyEKkwwy3J8e46jqSAJK54AI0',
    appId: '1:862847817672:ios:1a7ea4006d3b31edb192fd',
    messagingSenderId: '862847817672',
    projectId: 'outtadebtdb',
    storageBucket: 'outtadebtdb.firebasestorage.app',
    iosBundleId: 'com.outtadebt.outtadebt',
  );

}